[package]
name = "belajar_rust_crate_say_hello"
version = "0.2.0"
edition = "2021"
description = "Hello library"
license = "Apache-2.0"
authors = ["Aninditya QS"]

[features]
greet = []
jam = []
all = ["greet", "jam"]
default = ["greet"]

[dependencies]
chrono = "0.4.38"
